// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Empresa;
import org.sigma.core.service.impl.EmpresaServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmpresaServiceImpl_Roo_Service {
    
    declare @type: EmpresaServiceImpl: @Service;
    
    declare @type: EmpresaServiceImpl: @Transactional;
    
    public long EmpresaServiceImpl.countAllEmpresas() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void EmpresaServiceImpl.deleteEmpresa(Empresa empresa) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Empresa EmpresaServiceImpl.findEmpresa(Integer id) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Empresa> EmpresaServiceImpl.findAllEmpresas() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Empresa> EmpresaServiceImpl.findEmpresaEntries(int firstResult, int maxResults) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void EmpresaServiceImpl.saveEmpresa(Empresa empresa) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Empresa EmpresaServiceImpl.updateEmpresa(Empresa empresa) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
}
