// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.service.impl.FuenteHidricaServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FuenteHidricaServiceImpl_Roo_Service {
    
    declare @type: FuenteHidricaServiceImpl: @Service;
    
    declare @type: FuenteHidricaServiceImpl: @Transactional;
    
    public long FuenteHidricaServiceImpl.countAllFuenteHidricas() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void FuenteHidricaServiceImpl.deleteFuenteHidrica(FuenteHidrica fuenteHidrica) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public FuenteHidrica FuenteHidricaServiceImpl.findFuenteHidrica(Integer id) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<FuenteHidrica> FuenteHidricaServiceImpl.findAllFuenteHidricas() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<FuenteHidrica> FuenteHidricaServiceImpl.findFuenteHidricaEntries(int firstResult, int maxResults) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void FuenteHidricaServiceImpl.saveFuenteHidrica(FuenteHidrica fuenteHidrica) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public FuenteHidrica FuenteHidricaServiceImpl.updateFuenteHidrica(FuenteHidrica fuenteHidrica) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
}
