// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.service.impl.ProyectoServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProyectoServiceImpl_Roo_Service {
    
    declare @type: ProyectoServiceImpl: @Service;
    
    declare @type: ProyectoServiceImpl: @Transactional;
    
    public long ProyectoServiceImpl.countAllProyectoes() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void ProyectoServiceImpl.deleteProyecto(Proyecto proyecto) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Proyecto ProyectoServiceImpl.findProyecto(Integer id) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Proyecto> ProyectoServiceImpl.findAllProyectoes() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Proyecto> ProyectoServiceImpl.findProyectoEntries(int firstResult, int maxResults) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void ProyectoServiceImpl.saveProyecto(Proyecto proyecto) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Proyecto ProyectoServiceImpl.updateProyecto(Proyecto proyecto) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
}
