// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Rol;
import org.sigma.core.service.impl.RolServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RolServiceImpl_Roo_Service {
    
    declare @type: RolServiceImpl: @Service;
    
    declare @type: RolServiceImpl: @Transactional;
    
    public long RolServiceImpl.countAllRols() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void RolServiceImpl.deleteRol(Rol rol) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Rol RolServiceImpl.findRol(Integer id) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Rol> RolServiceImpl.findAllRols() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<Rol> RolServiceImpl.findRolEntries(int firstResult, int maxResults) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void RolServiceImpl.saveRol(Rol rol) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public Rol RolServiceImpl.updateRol(Rol rol) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
}
