// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.User;
import org.sigma.core.service.impl.UserServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserServiceImpl_Roo_Service {
    
    declare @type: UserServiceImpl: @Service;
    
    declare @type: UserServiceImpl: @Transactional;
    
    public long UserServiceImpl.countAllUsers() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void UserServiceImpl.deleteUser(User user) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public User UserServiceImpl.findUser(Integer id) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<User> UserServiceImpl.findAllUsers() {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public List<User> UserServiceImpl.findUserEntries(int firstResult, int maxResults) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public void UserServiceImpl.saveUser(User user) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
    public User UserServiceImpl.updateUser(User user) {
        throw new UnsupportedOperationException("Implement me!");
    }
    
}
