// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service;

import java.util.List;
import org.sigma.core.domain.Parametro;
import org.sigma.core.service.ParametroService;

privileged aspect ParametroService_Roo_Service {
    
    public abstract long ParametroService.countAllParametroes();    
    public abstract void ParametroService.deleteParametro(Parametro parametro);    
    public abstract Parametro ParametroService.findParametro(Integer id);    
    public abstract List<Parametro> ParametroService.findAllParametroes();    
    public abstract List<Parametro> ParametroService.findParametroEntries(int firstResult, int maxResults);    
    public abstract void ParametroService.saveParametro(Parametro parametro);    
    public abstract Parametro ParametroService.updateParametro(Parametro parametro);    
}
