// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service;

import java.util.List;
import org.sigma.core.domain.Rol;
import org.sigma.core.service.RolService;

privileged aspect RolService_Roo_Service {
    
    public abstract long RolService.countAllRols();    
    public abstract void RolService.deleteRol(Rol rol);    
    public abstract Rol RolService.findRol(Integer id);    
    public abstract List<Rol> RolService.findAllRols();    
    public abstract List<Rol> RolService.findRolEntries(int firstResult, int maxResults);    
    public abstract void RolService.saveRol(Rol rol);    
    public abstract Rol RolService.updateRol(Rol rol);    
}
