// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.repository;

import org.sigma.core.domain.Empresa;
import org.sigma.core.repository.EmpresaRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect EmpresaRepository_Roo_Jpa_Repository {
    
    declare parents: EmpresaRepository extends JpaRepository<Empresa, Integer>;
    
    declare parents: EmpresaRepository extends JpaSpecificationExecutor<Empresa>;
    
    declare @type: EmpresaRepository: @Repository;
    
}
