// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.repository;

import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.repository.FuenteHidricaRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FuenteHidricaRepository_Roo_Jpa_Repository {
    
    declare parents: FuenteHidricaRepository extends JpaRepository<FuenteHidrica, Integer>;
    
    declare parents: FuenteHidricaRepository extends JpaSpecificationExecutor<FuenteHidrica>;
    
    declare @type: FuenteHidricaRepository: @Repository;
    
}
