// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.repository;

import org.sigma.core.domain.Muestra;
import org.sigma.core.repository.MuestraRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect MuestraRepository_Roo_Jpa_Repository {
    
    declare parents: MuestraRepository extends JpaRepository<Muestra, Integer>;
    
    declare parents: MuestraRepository extends JpaSpecificationExecutor<Muestra>;
    
    declare @type: MuestraRepository: @Repository;
    
}
