// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.repository;

import org.sigma.core.domain.Parametro;
import org.sigma.core.repository.ParametroRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ParametroRepository_Roo_Jpa_Repository {
    
    declare parents: ParametroRepository extends JpaRepository<Parametro, Integer>;
    
    declare parents: ParametroRepository extends JpaSpecificationExecutor<Parametro>;
    
    declare @type: ParametroRepository: @Repository;
    
}
