// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.repository;

import org.sigma.core.domain.Proyecto;
import org.sigma.core.repository.ProyectoRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ProyectoRepository_Roo_Jpa_Repository {
    
    declare parents: ProyectoRepository extends JpaRepository<Proyecto, Integer>;
    
    declare parents: ProyectoRepository extends JpaSpecificationExecutor<Proyecto>;
    
    declare @type: ProyectoRepository: @Repository;
    
}
