// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service;

import java.util.List;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.service.FuenteHidricaService;

privileged aspect FuenteHidricaService_Roo_Service {
    
    public abstract long FuenteHidricaService.countAllFuenteHidricas();    
    public abstract void FuenteHidricaService.deleteFuenteHidrica(FuenteHidrica fuenteHidrica);    
    public abstract FuenteHidrica FuenteHidricaService.findFuenteHidrica(Integer id);    
    public abstract List<FuenteHidrica> FuenteHidricaService.findAllFuenteHidricas();    
    public abstract List<FuenteHidrica> FuenteHidricaService.findFuenteHidricaEntries(int firstResult, int maxResults);    
    public abstract void FuenteHidricaService.saveFuenteHidrica(FuenteHidrica fuenteHidrica);    
    public abstract FuenteHidrica FuenteHidricaService.updateFuenteHidrica(FuenteHidrica fuenteHidrica);    
}
