// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service;

import java.util.List;
import org.sigma.core.domain.Muestra;
import org.sigma.core.service.MuestraService;

privileged aspect MuestraService_Roo_Service {
    
    public abstract long MuestraService.countAllMuestras();    
    public abstract void MuestraService.deleteMuestra(Muestra muestra);    
    public abstract Muestra MuestraService.findMuestra(Integer id);    
    public abstract List<Muestra> MuestraService.findAllMuestras();    
    public abstract List<Muestra> MuestraService.findMuestraEntries(int firstResult, int maxResults);    
    public abstract void MuestraService.saveMuestra(Muestra muestra);    
    public abstract Muestra MuestraService.updateMuestra(Muestra muestra);    
}
