// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service;

import java.util.List;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.service.ProyectoService;

privileged aspect ProyectoService_Roo_Service {
    
    public abstract long ProyectoService.countAllProyectoes();    
    public abstract void ProyectoService.deleteProyecto(Proyecto proyecto);    
    public abstract Proyecto ProyectoService.findProyecto(Integer id);    
    public abstract List<Proyecto> ProyectoService.findAllProyectoes();    
    public abstract List<Proyecto> ProyectoService.findProyectoEntries(int firstResult, int maxResults);    
    public abstract void ProyectoService.saveProyecto(Proyecto proyecto);    
    public abstract Proyecto ProyectoService.updateProyecto(Proyecto proyecto);    
}
