// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Empresa;
import org.sigma.core.repository.EmpresaRepository;
import org.sigma.core.service.impl.EmpresaServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmpresaServiceImpl_Roo_Service {
    
    declare @type: EmpresaServiceImpl: @Service;
    
    declare @type: EmpresaServiceImpl: @Transactional;
    
    @Autowired
    EmpresaRepository EmpresaServiceImpl.empresaRepository;
    
    public long EmpresaServiceImpl.countAllEmpresas() {
        return empresaRepository.count();
    }
    
    public void EmpresaServiceImpl.deleteEmpresa(Empresa empresa) {
        empresaRepository.delete(empresa);
    }
    
    public Empresa EmpresaServiceImpl.findEmpresa(Integer id) {
        return empresaRepository.findOne(id);
    }
    
    public List<Empresa> EmpresaServiceImpl.findAllEmpresas() {
        return empresaRepository.findAll();
    }
    
    public List<Empresa> EmpresaServiceImpl.findEmpresaEntries(int firstResult, int maxResults) {
        return empresaRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void EmpresaServiceImpl.saveEmpresa(Empresa empresa) {
        empresaRepository.save(empresa);
    }
    
    public Empresa EmpresaServiceImpl.updateEmpresa(Empresa empresa) {
        return empresaRepository.save(empresa);
    }
    
}
