// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Muestra;
import org.sigma.core.repository.MuestraRepository;
import org.sigma.core.service.impl.MuestraServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MuestraServiceImpl_Roo_Service {
    
    declare @type: MuestraServiceImpl: @Service;
    
    declare @type: MuestraServiceImpl: @Transactional;
    
    @Autowired
    MuestraRepository MuestraServiceImpl.muestraRepository;
    
    public long MuestraServiceImpl.countAllMuestras() {
        return muestraRepository.count();
    }
    
    public void MuestraServiceImpl.deleteMuestra(Muestra muestra) {
        muestraRepository.delete(muestra);
    }
    
    public Muestra MuestraServiceImpl.findMuestra(Integer id) {
        return muestraRepository.findOne(id);
    }
    
    public List<Muestra> MuestraServiceImpl.findAllMuestras() {
        return muestraRepository.findAll();
    }
    
    public List<Muestra> MuestraServiceImpl.findMuestraEntries(int firstResult, int maxResults) {
        return muestraRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void MuestraServiceImpl.saveMuestra(Muestra muestra) {
        muestraRepository.save(muestra);
    }
    
    public Muestra MuestraServiceImpl.updateMuestra(Muestra muestra) {
        return muestraRepository.save(muestra);
    }
    
}
