// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.repository.ProyectoRepository;
import org.sigma.core.service.impl.ProyectoServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProyectoServiceImpl_Roo_Service {
    
    declare @type: ProyectoServiceImpl: @Service;
    
    declare @type: ProyectoServiceImpl: @Transactional;
    
    @Autowired
    ProyectoRepository ProyectoServiceImpl.proyectoRepository;
    
    public long ProyectoServiceImpl.countAllProyectoes() {
        return proyectoRepository.count();
    }
    
    public void ProyectoServiceImpl.deleteProyecto(Proyecto proyecto) {
        proyectoRepository.delete(proyecto);
    }
    
    public Proyecto ProyectoServiceImpl.findProyecto(Integer id) {
        return proyectoRepository.findOne(id);
    }
    
    public List<Proyecto> ProyectoServiceImpl.findAllProyectoes() {
        return proyectoRepository.findAll();
    }
    
    public List<Proyecto> ProyectoServiceImpl.findProyectoEntries(int firstResult, int maxResults) {
        return proyectoRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void ProyectoServiceImpl.saveProyecto(Proyecto proyecto) {
        proyectoRepository.save(proyecto);
    }
    
    public Proyecto ProyectoServiceImpl.updateProyecto(Proyecto proyecto) {
        return proyectoRepository.save(proyecto);
    }
    
}
