// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.service.impl;

import java.util.List;
import org.sigma.core.domain.Rol;
import org.sigma.core.repository.RolRepository;
import org.sigma.core.service.impl.RolServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RolServiceImpl_Roo_Service {
    
    declare @type: RolServiceImpl: @Service;
    
    declare @type: RolServiceImpl: @Transactional;
    
    @Autowired
    RolRepository RolServiceImpl.rolRepository;
    
    public long RolServiceImpl.countAllRols() {
        return rolRepository.count();
    }
    
    public void RolServiceImpl.deleteRol(Rol rol) {
        rolRepository.delete(rol);
    }
    
    public Rol RolServiceImpl.findRol(Integer id) {
        return rolRepository.findOne(id);
    }
    
    public List<Rol> RolServiceImpl.findAllRols() {
        return rolRepository.findAll();
    }
    
    public List<Rol> RolServiceImpl.findRolEntries(int firstResult, int maxResults) {
        return rolRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void RolServiceImpl.saveRol(Rol rol) {
        rolRepository.save(rol);
    }
    
    public Rol RolServiceImpl.updateRol(Rol rol) {
        return rolRepository.save(rol);
    }
    
}
