// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.web;

import org.sigma.core.domain.Empresa;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.domain.Muestra;
import org.sigma.core.domain.Parametro;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.domain.Rol;
import org.sigma.core.domain.User;
import org.sigma.core.service.EmpresaService;
import org.sigma.core.service.FuenteHidricaService;
import org.sigma.core.service.MuestraService;
import org.sigma.core.service.ParametroService;
import org.sigma.core.service.ProyectoService;
import org.sigma.core.service.RolService;
import org.sigma.core.service.UserService;
import org.sigma.core.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    @Autowired
    EmpresaService ApplicationConversionServiceFactoryBean.empresaService;
    
    @Autowired
    FuenteHidricaService ApplicationConversionServiceFactoryBean.fuenteHidricaService;
    
    @Autowired
    MuestraService ApplicationConversionServiceFactoryBean.muestraService;
    
    @Autowired
    ParametroService ApplicationConversionServiceFactoryBean.parametroService;
    
    @Autowired
    ProyectoService ApplicationConversionServiceFactoryBean.proyectoService;
    
    @Autowired
    RolService ApplicationConversionServiceFactoryBean.rolService;
    
    @Autowired
    UserService ApplicationConversionServiceFactoryBean.userService;
    
    public Converter<Empresa, String> ApplicationConversionServiceFactoryBean.getEmpresaToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.Empresa, java.lang.String>() {
            public String convert(Empresa empresa) {
                return new StringBuilder().append(empresa.getTipoempresa()).append(' ').append(empresa.getNombre()).append(' ').append(empresa.getRepresentantelegal()).append(' ').append(empresa.getRut()).toString();
            }
        };
    }
    
    public Converter<Integer, Empresa> ApplicationConversionServiceFactoryBean.getIdToEmpresaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.Empresa>() {
            public org.sigma.core.domain.Empresa convert(java.lang.Integer id) {
                return empresaService.findEmpresa(id);
            }
        };
    }
    
    public Converter<String, Empresa> ApplicationConversionServiceFactoryBean.getStringToEmpresaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.Empresa>() {
            public org.sigma.core.domain.Empresa convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Empresa.class);
            }
        };
    }
    
    public Converter<FuenteHidrica, String> ApplicationConversionServiceFactoryBean.getFuenteHidricaToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.FuenteHidrica, java.lang.String>() {
            public String convert(FuenteHidrica fuenteHidrica) {
                return new StringBuilder().append(fuenteHidrica.getGeometria()).append(' ').append(fuenteHidrica.getNombre()).toString();
            }
        };
    }
    
    public Converter<Integer, FuenteHidrica> ApplicationConversionServiceFactoryBean.getIdToFuenteHidricaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.FuenteHidrica>() {
            public org.sigma.core.domain.FuenteHidrica convert(java.lang.Integer id) {
                return fuenteHidricaService.findFuenteHidrica(id);
            }
        };
    }
    
    public Converter<String, FuenteHidrica> ApplicationConversionServiceFactoryBean.getStringToFuenteHidricaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.FuenteHidrica>() {
            public org.sigma.core.domain.FuenteHidrica convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), FuenteHidrica.class);
            }
        };
    }
    
    public Converter<Muestra, String> ApplicationConversionServiceFactoryBean.getMuestraToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.Muestra, java.lang.String>() {
            public String convert(Muestra muestra) {
                return new StringBuilder().append(muestra.getResponsable()).append(' ').append(muestra.getProducto()).append(' ').append(muestra.getLugarToma()).append(' ').append(muestra.getFoto()).toString();
            }
        };
    }
    
    public Converter<Integer, Muestra> ApplicationConversionServiceFactoryBean.getIdToMuestraConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.Muestra>() {
            public org.sigma.core.domain.Muestra convert(java.lang.Integer id) {
                return muestraService.findMuestra(id);
            }
        };
    }
    
    public Converter<String, Muestra> ApplicationConversionServiceFactoryBean.getStringToMuestraConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.Muestra>() {
            public org.sigma.core.domain.Muestra convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Muestra.class);
            }
        };
    }
    
    public Converter<Parametro, String> ApplicationConversionServiceFactoryBean.getParametroToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.Parametro, java.lang.String>() {
            public String convert(Parametro parametro) {
                return new StringBuilder().append(parametro.getNombre()).append(' ').append(parametro.getUnidad()).append(' ').append(parametro.getConcentracion()).append(' ').append(parametro.getTecAnalitic()).toString();
            }
        };
    }
    
    public Converter<Integer, Parametro> ApplicationConversionServiceFactoryBean.getIdToParametroConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.Parametro>() {
            public org.sigma.core.domain.Parametro convert(java.lang.Integer id) {
                return parametroService.findParametro(id);
            }
        };
    }
    
    public Converter<String, Parametro> ApplicationConversionServiceFactoryBean.getStringToParametroConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.Parametro>() {
            public org.sigma.core.domain.Parametro convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Parametro.class);
            }
        };
    }
    
    public Converter<Proyecto, String> ApplicationConversionServiceFactoryBean.getProyectoToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.Proyecto, java.lang.String>() {
            public String convert(Proyecto proyecto) {
                return new StringBuilder().append(proyecto.getInvolucrados()).append(' ').append(proyecto.getNombre()).append(' ').append(proyecto.getEncargado()).toString();
            }
        };
    }
    
    public Converter<Integer, Proyecto> ApplicationConversionServiceFactoryBean.getIdToProyectoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.Proyecto>() {
            public org.sigma.core.domain.Proyecto convert(java.lang.Integer id) {
                return proyectoService.findProyecto(id);
            }
        };
    }
    
    public Converter<String, Proyecto> ApplicationConversionServiceFactoryBean.getStringToProyectoConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.Proyecto>() {
            public org.sigma.core.domain.Proyecto convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Proyecto.class);
            }
        };
    }
    
    public Converter<Rol, String> ApplicationConversionServiceFactoryBean.getRolToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.Rol, java.lang.String>() {
            public String convert(Rol rol) {
                return new StringBuilder().append(rol.getNombre()).toString();
            }
        };
    }
    
    public Converter<Integer, Rol> ApplicationConversionServiceFactoryBean.getIdToRolConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.Rol>() {
            public org.sigma.core.domain.Rol convert(java.lang.Integer id) {
                return rolService.findRol(id);
            }
        };
    }
    
    public Converter<String, Rol> ApplicationConversionServiceFactoryBean.getStringToRolConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.Rol>() {
            public org.sigma.core.domain.Rol convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), Rol.class);
            }
        };
    }
    
    public Converter<User, String> ApplicationConversionServiceFactoryBean.getUserToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<org.sigma.core.domain.User, java.lang.String>() {
            public String convert(User user) {
                return new StringBuilder().append(user.getAlias()).append(' ').append(user.getMail()).append(' ').append(user.getNombre()).toString();
            }
        };
    }
    
    public Converter<Integer, User> ApplicationConversionServiceFactoryBean.getIdToUserConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Integer, org.sigma.core.domain.User>() {
            public org.sigma.core.domain.User convert(java.lang.Integer id) {
                return userService.findUser(id);
            }
        };
    }
    
    public Converter<String, User> ApplicationConversionServiceFactoryBean.getStringToUserConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, org.sigma.core.domain.User>() {
            public org.sigma.core.domain.User convert(String id) {
                return getObject().convert(getObject().convert(id, Integer.class), User.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getEmpresaToStringConverter());
        registry.addConverter(getIdToEmpresaConverter());
        registry.addConverter(getStringToEmpresaConverter());
        registry.addConverter(getFuenteHidricaToStringConverter());
        registry.addConverter(getIdToFuenteHidricaConverter());
        registry.addConverter(getStringToFuenteHidricaConverter());
        registry.addConverter(getMuestraToStringConverter());
        registry.addConverter(getIdToMuestraConverter());
        registry.addConverter(getStringToMuestraConverter());
        registry.addConverter(getParametroToStringConverter());
        registry.addConverter(getIdToParametroConverter());
        registry.addConverter(getStringToParametroConverter());
        registry.addConverter(getProyectoToStringConverter());
        registry.addConverter(getIdToProyectoConverter());
        registry.addConverter(getStringToProyectoConverter());
        registry.addConverter(getRolToStringConverter());
        registry.addConverter(getIdToRolConverter());
        registry.addConverter(getStringToRolConverter());
        registry.addConverter(getUserToStringConverter());
        registry.addConverter(getIdToUserConverter());
        registry.addConverter(getStringToUserConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
