// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.service.FuenteHidricaService;
import org.sigma.core.service.MuestraService;
import org.sigma.core.service.ProyectoService;
import org.sigma.core.web.FuenteHidricaController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FuenteHidricaController_Roo_Controller {
    
    @Autowired
    FuenteHidricaService FuenteHidricaController.fuenteHidricaService;
    
    @Autowired
    MuestraService FuenteHidricaController.muestraService;
    
    @Autowired
    ProyectoService FuenteHidricaController.proyectoService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FuenteHidricaController.create(@Valid FuenteHidrica fuenteHidrica, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, fuenteHidrica);
            return "fuentehidricas/create";
        }
        uiModel.asMap().clear();
        fuenteHidricaService.saveFuenteHidrica(fuenteHidrica);
        return "redirect:/fuentehidricas/" + encodeUrlPathSegment(fuenteHidrica.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FuenteHidricaController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FuenteHidrica());
        return "fuentehidricas/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FuenteHidricaController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("fuentehidrica", fuenteHidricaService.findFuenteHidrica(id));
        uiModel.addAttribute("itemId", id);
        return "fuentehidricas/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FuenteHidricaController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("fuentehidricas", fuenteHidricaService.findFuenteHidricaEntries(firstResult, sizeNo));
            float nrOfPages = (float) fuenteHidricaService.countAllFuenteHidricas() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("fuentehidricas", fuenteHidricaService.findAllFuenteHidricas());
        }
        return "fuentehidricas/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FuenteHidricaController.update(@Valid FuenteHidrica fuenteHidrica, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, fuenteHidrica);
            return "fuentehidricas/update";
        }
        uiModel.asMap().clear();
        fuenteHidricaService.updateFuenteHidrica(fuenteHidrica);
        return "redirect:/fuentehidricas/" + encodeUrlPathSegment(fuenteHidrica.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FuenteHidricaController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, fuenteHidricaService.findFuenteHidrica(id));
        return "fuentehidricas/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FuenteHidricaController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FuenteHidrica fuenteHidrica = fuenteHidricaService.findFuenteHidrica(id);
        fuenteHidricaService.deleteFuenteHidrica(fuenteHidrica);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/fuentehidricas";
    }
    
    void FuenteHidricaController.populateEditForm(Model uiModel, FuenteHidrica fuenteHidrica) {
        uiModel.addAttribute("fuenteHidrica", fuenteHidrica);
        uiModel.addAttribute("muestras", muestraService.findAllMuestras());
        uiModel.addAttribute("proyectoes", proyectoService.findAllProyectoes());
    }
    
    String FuenteHidricaController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
