// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.sigma.core.domain.Muestra;
import org.sigma.core.service.FuenteHidricaService;
import org.sigma.core.service.MuestraService;
import org.sigma.core.service.ParametroService;
import org.sigma.core.web.MuestraController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect MuestraController_Roo_Controller {
    
    @Autowired
    MuestraService MuestraController.muestraService;
    
    @Autowired
    FuenteHidricaService MuestraController.fuenteHidricaService;
    
    @Autowired
    ParametroService MuestraController.parametroService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String MuestraController.create(@Valid Muestra muestra, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, muestra);
            return "muestras/create";
        }
        uiModel.asMap().clear();
        muestraService.saveMuestra(muestra);
        return "redirect:/muestras/" + encodeUrlPathSegment(muestra.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String MuestraController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Muestra());
        return "muestras/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String MuestraController.show(@PathVariable("id") Integer id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("muestra", muestraService.findMuestra(id));
        uiModel.addAttribute("itemId", id);
        return "muestras/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String MuestraController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("muestras", muestraService.findMuestraEntries(firstResult, sizeNo));
            float nrOfPages = (float) muestraService.countAllMuestras() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("muestras", muestraService.findAllMuestras());
        }
        addDateTimeFormatPatterns(uiModel);
        return "muestras/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String MuestraController.update(@Valid Muestra muestra, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, muestra);
            return "muestras/update";
        }
        uiModel.asMap().clear();
        muestraService.updateMuestra(muestra);
        return "redirect:/muestras/" + encodeUrlPathSegment(muestra.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String MuestraController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, muestraService.findMuestra(id));
        return "muestras/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String MuestraController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Muestra muestra = muestraService.findMuestra(id);
        muestraService.deleteMuestra(muestra);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/muestras";
    }
    
    void MuestraController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("muestra_fechatoma_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("muestra_fecharecepcion_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
        uiModel.addAttribute("muestra_fechaanalisis_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void MuestraController.populateEditForm(Model uiModel, Muestra muestra) {
        uiModel.addAttribute("muestra", muestra);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("fuentehidricas", fuenteHidricaService.findAllFuenteHidricas());
        uiModel.addAttribute("parametroes", parametroService.findAllParametroes());
    }
    
    String MuestraController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
