// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.service.EmpresaService;
import org.sigma.core.service.FuenteHidricaService;
import org.sigma.core.service.ProyectoService;
import org.sigma.core.web.ProyectoController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ProyectoController_Roo_Controller {
    
    @Autowired
    ProyectoService ProyectoController.proyectoService;
    
    @Autowired
    EmpresaService ProyectoController.empresaService;
    
    @Autowired
    FuenteHidricaService ProyectoController.fuenteHidricaService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ProyectoController.create(@Valid Proyecto proyecto, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, proyecto);
            return "proyectoes/create";
        }
        uiModel.asMap().clear();
        proyectoService.saveProyecto(proyecto);
        return "redirect:/proyectoes/" + encodeUrlPathSegment(proyecto.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ProyectoController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Proyecto());
        return "proyectoes/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ProyectoController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("proyecto", proyectoService.findProyecto(id));
        uiModel.addAttribute("itemId", id);
        return "proyectoes/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ProyectoController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("proyectoes", proyectoService.findProyectoEntries(firstResult, sizeNo));
            float nrOfPages = (float) proyectoService.countAllProyectoes() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("proyectoes", proyectoService.findAllProyectoes());
        }
        return "proyectoes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ProyectoController.update(@Valid Proyecto proyecto, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, proyecto);
            return "proyectoes/update";
        }
        uiModel.asMap().clear();
        proyectoService.updateProyecto(proyecto);
        return "redirect:/proyectoes/" + encodeUrlPathSegment(proyecto.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ProyectoController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, proyectoService.findProyecto(id));
        return "proyectoes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ProyectoController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Proyecto proyecto = proyectoService.findProyecto(id);
        proyectoService.deleteProyecto(proyecto);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/proyectoes";
    }
    
    void ProyectoController.populateEditForm(Model uiModel, Proyecto proyecto) {
        uiModel.addAttribute("proyecto", proyecto);
        uiModel.addAttribute("empresas", empresaService.findAllEmpresas());
        uiModel.addAttribute("fuentehidricas", fuenteHidricaService.findAllFuenteHidricas());
    }
    
    String ProyectoController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
