// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.sigma.core.domain.Empresa;

privileged aspect Empresa_Roo_Jpa_Entity {
    
    declare @type: Empresa: @Entity;
    
    declare @type: Empresa: @Table(schema = "public", name = "empresa");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer Empresa.id;
    
    public Integer Empresa.getId() {
        return this.id;
    }
    
    public void Empresa.setId(Integer id) {
        this.id = id;
    }
    
}
