// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.domain.Muestra;
import org.sigma.core.domain.Parametro;
import org.springframework.format.annotation.DateTimeFormat;

privileged aspect Muestra_Roo_DbManaged {
    
    @ManyToMany
    @JoinTable(name = "many_muestra_has_many_parametro", joinColumns = { @JoinColumn(name = "id_muestra", nullable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_parametro", nullable = false) })
    private Set<Parametro> Muestra.parametroes;
    
    @ManyToOne
    @JoinColumn(name = "id_fuente_hidrica", referencedColumnName = "id")
    private FuenteHidrica Muestra.idFuenteHidrica;
    
    @Column(name = "responsable")
    private String Muestra.responsable;
    
    @Column(name = "producto")
    private String Muestra.producto;
    
    @Column(name = "lugar_toma")
    private String Muestra.lugarToma;
    
    @Column(name = "foto")
    private String Muestra.foto;
    
    @Column(name = "n_muestras")
    private Integer Muestra.nMuestras;
    
    @Column(name = "fecha_toma")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Muestra.fechaToma;
    
    @Column(name = "fecha_recepcion")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Muestra.fechaRecepcion;
    
    @Column(name = "fecha_analisis")
    @Temporal(TemporalType.DATE)
    @DateTimeFormat(style = "M-")
    private Date Muestra.fechaAnalisis;
    
    @Column(name = "tipo_muestreo")
    private String Muestra.tipoMuestreo;
    
    public Set<Parametro> Muestra.getParametroes() {
        return parametroes;
    }
    
    public void Muestra.setParametroes(Set<Parametro> parametroes) {
        this.parametroes = parametroes;
    }
    
    public FuenteHidrica Muestra.getIdFuenteHidrica() {
        return idFuenteHidrica;
    }
    
    public void Muestra.setIdFuenteHidrica(FuenteHidrica idFuenteHidrica) {
        this.idFuenteHidrica = idFuenteHidrica;
    }
    
    public String Muestra.getResponsable() {
        return responsable;
    }
    
    public void Muestra.setResponsable(String responsable) {
        this.responsable = responsable;
    }
    
    public String Muestra.getProducto() {
        return producto;
    }
    
    public void Muestra.setProducto(String producto) {
        this.producto = producto;
    }
    
    public String Muestra.getLugarToma() {
        return lugarToma;
    }
    
    public void Muestra.setLugarToma(String lugarToma) {
        this.lugarToma = lugarToma;
    }
    
    public String Muestra.getFoto() {
        return foto;
    }
    
    public void Muestra.setFoto(String foto) {
        this.foto = foto;
    }
    
    public Integer Muestra.getNMuestras() {
        return nMuestras;
    }
    
    public void Muestra.setNMuestras(Integer nMuestras) {
        this.nMuestras = nMuestras;
    }
    
    public Date Muestra.getFechaToma() {
        return fechaToma;
    }
    
    public void Muestra.setFechaToma(Date fechaToma) {
        this.fechaToma = fechaToma;
    }
    
    public Date Muestra.getFechaRecepcion() {
        return fechaRecepcion;
    }
    
    public void Muestra.setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    
    public Date Muestra.getFechaAnalisis() {
        return fechaAnalisis;
    }
    
    public void Muestra.setFechaAnalisis(Date fechaAnalisis) {
        this.fechaAnalisis = fechaAnalisis;
    }
    
    public String Muestra.getTipoMuestreo() {
        return tipoMuestreo;
    }
    
    public void Muestra.setTipoMuestreo(String tipoMuestreo) {
        this.tipoMuestreo = tipoMuestreo;
    }
    
}
