// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.sigma.core.domain.Muestra;

privileged aspect Muestra_Roo_Jpa_Entity {
    
    declare @type: Muestra: @Entity;
    
    declare @type: Muestra: @Table(schema = "public", name = "muestra");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer Muestra.id;
    
    public Integer Muestra.getId() {
        return this.id;
    }
    
    public void Muestra.setId(Integer id) {
        this.id = id;
    }
    
}
