// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import org.sigma.core.domain.Rol;
import org.sigma.core.domain.User;

privileged aspect Rol_Roo_DbManaged {
    
    @ManyToMany
    @JoinTable(name = "many_user_has_many_rol", joinColumns = { @JoinColumn(name = "id_rol", nullable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_user", nullable = false) })
    private Set<User> Rol.users;
    
    @Column(name = "nombre")
    private String Rol.nombre;
    
    public Set<User> Rol.getUsers() {
        return users;
    }
    
    public void Rol.setUsers(Set<User> users) {
        this.users = users;
    }
    
    public String Rol.getNombre() {
        return nombre;
    }
    
    public void Rol.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
