// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import org.sigma.core.domain.Empresa;
import org.sigma.core.domain.Proyecto;
import org.sigma.core.domain.Usuario;

privileged aspect Empresa_Roo_DbManaged {
    
    @ManyToMany
    @JoinTable(name = "many_proyecto_has_many_empresa", joinColumns = { @JoinColumn(name = "id_empresa", nullable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_proyecto", nullable = false) })
    private Set<Proyecto> Empresa.proyectoes;
    
    @OneToMany(mappedBy = "idEmpresa", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    private Set<Usuario> Empresa.usuarios;
    
    @Column(name = "tipoempresa")
    private String Empresa.tipoempresa;
    
    @Column(name = "nombre")
    private String Empresa.nombre;
    
    @Column(name = "representantelegal")
    private String Empresa.representantelegal;
    
    @Column(name = "rut")
    private String Empresa.rut;
    
    @Column(name = "nit")
    private String Empresa.nit;
    
    @Column(name = "email")
    private String Empresa.email;
    
    @Column(name = "ciudad")
    private String Empresa.ciudad;
    
    @Column(name = "direccion")
    private String Empresa.direccion;
    
    public Set<Proyecto> Empresa.getProyectoes() {
        return proyectoes;
    }
    
    public void Empresa.setProyectoes(Set<Proyecto> proyectoes) {
        this.proyectoes = proyectoes;
    }
    
    public Set<Usuario> Empresa.getUsuarios() {
        return usuarios;
    }
    
    public void Empresa.setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    
    public String Empresa.getTipoempresa() {
        return tipoempresa;
    }
    
    public void Empresa.setTipoempresa(String tipoempresa) {
        this.tipoempresa = tipoempresa;
    }
    
    public String Empresa.getNombre() {
        return nombre;
    }
    
    public void Empresa.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String Empresa.getRepresentantelegal() {
        return representantelegal;
    }
    
    public void Empresa.setRepresentantelegal(String representantelegal) {
        this.representantelegal = representantelegal;
    }
    
    public String Empresa.getRut() {
        return rut;
    }
    
    public void Empresa.setRut(String rut) {
        this.rut = rut;
    }
    
    public String Empresa.getNit() {
        return nit;
    }
    
    public void Empresa.setNit(String nit) {
        this.nit = nit;
    }
    
    public String Empresa.getEmail() {
        return email;
    }
    
    public void Empresa.setEmail(String email) {
        this.email = email;
    }
    
    public String Empresa.getCiudad() {
        return ciudad;
    }
    
    public void Empresa.setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    
    public String Empresa.getDireccion() {
        return direccion;
    }
    
    public void Empresa.setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
}
