// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.domain.Muestra;
import org.sigma.core.domain.Proyecto;

privileged aspect FuenteHidrica_Roo_DbManaged {
    
    @ManyToMany
    @JoinTable(name = "many_proyecto_has_many_fuente_hidrica", joinColumns = { @JoinColumn(name = "id_fuente_hidrica", nullable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_proyecto", nullable = false) })
    private Set<Proyecto> FuenteHidrica.proyectoes;
    
    @OneToMany(mappedBy = "idFuenteHidrica", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    private Set<Muestra> FuenteHidrica.muestras;
    
    @Column(name = "geometria")
    private String FuenteHidrica.geometria;
    
    @Column(name = "nombre")
    private String FuenteHidrica.nombre;
    
    public Set<Proyecto> FuenteHidrica.getProyectoes() {
        return proyectoes;
    }
    
    public void FuenteHidrica.setProyectoes(Set<Proyecto> proyectoes) {
        this.proyectoes = proyectoes;
    }
    
    public Set<Muestra> FuenteHidrica.getMuestras() {
        return muestras;
    }
    
    public void FuenteHidrica.setMuestras(Set<Muestra> muestras) {
        this.muestras = muestras;
    }
    
    public String FuenteHidrica.getGeometria() {
        return geometria;
    }
    
    public void FuenteHidrica.setGeometria(String geometria) {
        this.geometria = geometria;
    }
    
    public String FuenteHidrica.getNombre() {
        return nombre;
    }
    
    public void FuenteHidrica.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
