// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.sigma.core.domain.ManyMuestraHasManyParametro;
import org.sigma.core.domain.ManyMuestraHasManyParametroPK;

privileged aspect ManyMuestraHasManyParametro_Roo_Jpa_Entity {
    
    declare @type: ManyMuestraHasManyParametro: @Entity;
    
    declare @type: ManyMuestraHasManyParametro: @Table(schema = "public", name = "many_muestra_has_many_parametro");
    
    @EmbeddedId
    private ManyMuestraHasManyParametroPK ManyMuestraHasManyParametro.id;
    
    public ManyMuestraHasManyParametroPK ManyMuestraHasManyParametro.getId() {
        return this.id;
    }
    
    public void ManyMuestraHasManyParametro.setId(ManyMuestraHasManyParametroPK id) {
        this.id = id;
    }
    
}
