// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.io.Serializable;
import org.sigma.core.domain.ManyMuestraHasManyParametroPK;

privileged aspect ManyMuestraHasManyParametroPK_Roo_Serializable {
    
    declare parents: ManyMuestraHasManyParametroPK implements Serializable;
    
    private static final long ManyMuestraHasManyParametroPK.serialVersionUID = 1L;
    
}
