// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.sigma.core.domain.ManyMuestraHasManyParametroPK;

privileged aspect ManyMuestraHasManyParametroPK_Roo_Identifier {
    
    declare @type: ManyMuestraHasManyParametroPK: @Embeddable;
    
    @Column(name = "id_muestra", nullable = false)
    private Integer ManyMuestraHasManyParametroPK.idMuestra;
    
    @Column(name = "id_parametro", nullable = false)
    private Integer ManyMuestraHasManyParametroPK.idParametro;
    
    public ManyMuestraHasManyParametroPK.new(Integer idMuestra, Integer idParametro) {
        super();
        this.idMuestra = idMuestra;
        this.idParametro = idParametro;
    }

    private ManyMuestraHasManyParametroPK.new() {
        super();
    }

    public Integer ManyMuestraHasManyParametroPK.getIdMuestra() {
        return idMuestra;
    }
    
    public Integer ManyMuestraHasManyParametroPK.getIdParametro() {
        return idParametro;
    }
    
}
