// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.sigma.core.domain.ManyMuestraHasManyParametro;
import org.sigma.core.domain.Muestra;
import org.sigma.core.domain.Parametro;

privileged aspect ManyMuestraHasManyParametro_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "id_muestra", referencedColumnName = "id", nullable = false, insertable = false, updatable = false)
    private Muestra ManyMuestraHasManyParametro.idMuestra;
    
    @ManyToOne
    @JoinColumn(name = "id_parametro", referencedColumnName = "id", nullable = false, insertable = false, updatable = false)
    private Parametro ManyMuestraHasManyParametro.idParametro;
    
    @Column(name = "concentracion", precision = 17, scale = 17)
    private Double ManyMuestraHasManyParametro.concentracion;
    
    @Column(name = "tec_analitic")
    private String ManyMuestraHasManyParametro.tecAnalitic;
    
    public Muestra ManyMuestraHasManyParametro.getIdMuestra() {
        return idMuestra;
    }
    
    public void ManyMuestraHasManyParametro.setIdMuestra(Muestra idMuestra) {
        this.idMuestra = idMuestra;
    }
    
    public Parametro ManyMuestraHasManyParametro.getIdParametro() {
        return idParametro;
    }
    
    public void ManyMuestraHasManyParametro.setIdParametro(Parametro idParametro) {
        this.idParametro = idParametro;
    }
    
    public Double ManyMuestraHasManyParametro.getConcentracion() {
        return concentracion;
    }
    
    public void ManyMuestraHasManyParametro.setConcentracion(Double concentracion) {
        this.concentracion = concentracion;
    }
    
    public String ManyMuestraHasManyParametro.getTecAnalitic() {
        return tecAnalitic;
    }
    
    public void ManyMuestraHasManyParametro.setTecAnalitic(String tecAnalitic) {
        this.tecAnalitic = tecAnalitic;
    }
    
}
