// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.sigma.core.domain.ManyMuestraHasManyParametroPK;

privileged aspect ManyMuestraHasManyParametroPK_Roo_Json {
    
    public String ManyMuestraHasManyParametroPK.toJson() {
        return new JSONSerializer()
        .exclude("*.class").serialize(this);
    }
    
    public String ManyMuestraHasManyParametroPK.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").serialize(this);
    }
    
    public static ManyMuestraHasManyParametroPK ManyMuestraHasManyParametroPK.fromJsonToManyMuestraHasManyParametroPK(String json) {
        return new JSONDeserializer<ManyMuestraHasManyParametroPK>()
        .use(null, ManyMuestraHasManyParametroPK.class).deserialize(json);
    }
    
    public static String ManyMuestraHasManyParametroPK.toJsonArray(Collection<ManyMuestraHasManyParametroPK> collection) {
        return new JSONSerializer()
        .exclude("*.class").serialize(collection);
    }
    
    public static String ManyMuestraHasManyParametroPK.toJsonArray(Collection<ManyMuestraHasManyParametroPK> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<ManyMuestraHasManyParametroPK> ManyMuestraHasManyParametroPK.fromJsonArrayToManyMuestraHasManyParametroPKs(String json) {
        return new JSONDeserializer<List<ManyMuestraHasManyParametroPK>>()
        .use("values", ManyMuestraHasManyParametroPK.class).deserialize(json);
    }
    
}
