// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ManyToMany;
import org.sigma.core.domain.Empresa;
import org.sigma.core.domain.FuenteHidrica;
import org.sigma.core.domain.Proyecto;

privileged aspect Proyecto_Roo_DbManaged {
    
    @ManyToMany(mappedBy = "proyectoes", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    private Set<Empresa> Proyecto.empresas;
    
    @ManyToMany(mappedBy = "proyectoes", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    private Set<FuenteHidrica> Proyecto.fuenteHidricas;
    
    @Column(name = "involucrados")
    private String Proyecto.involucrados;
    
    @Column(name = "nombre")
    private String Proyecto.nombre;
    
    @Column(name = "encargado")
    private String Proyecto.encargado;
    
    public Set<Empresa> Proyecto.getEmpresas() {
        return empresas;
    }
    
    public void Proyecto.setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    
    public Set<FuenteHidrica> Proyecto.getFuenteHidricas() {
        return fuenteHidricas;
    }
    
    public void Proyecto.setFuenteHidricas(Set<FuenteHidrica> fuenteHidricas) {
        this.fuenteHidricas = fuenteHidricas;
    }
    
    public String Proyecto.getInvolucrados() {
        return involucrados;
    }
    
    public void Proyecto.setInvolucrados(String involucrados) {
        this.involucrados = involucrados;
    }
    
    public String Proyecto.getNombre() {
        return nombre;
    }
    
    public void Proyecto.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String Proyecto.getEncargado() {
        return encargado;
    }
    
    public void Proyecto.setEncargado(String encargado) {
        this.encargado = encargado;
    }
    
}
