// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import org.sigma.core.domain.Rol;
import org.sigma.core.domain.Usuario;

privileged aspect Rol_Roo_DbManaged {
    
    @OneToMany(mappedBy = "idRol", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    private Set<Usuario> Rol.usuarios;
    
    @Column(name = "nombre")
    private String Rol.nombre;
    
    public Set<Usuario> Rol.getUsuarios() {
        return usuarios;
    }
    
    public void Rol.setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    
    public String Rol.getNombre() {
        return nombre;
    }
    
    public void Rol.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
