// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.sigma.core.domain.SpatialRefSys;

privileged aspect SpatialRefSys_Roo_Jpa_Entity {
    
    declare @type: SpatialRefSys: @Entity;
    
    declare @type: SpatialRefSys: @Table(schema = "public", name = "spatial_ref_sys");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "srid")
    private Integer SpatialRefSys.srid;
    
    public Integer SpatialRefSys.getSrid() {
        return this.srid;
    }
    
    public void SpatialRefSys.setSrid(Integer id) {
        this.srid = id;
    }
    
}
