// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sigma.core.domain;

import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.sigma.core.domain.Empresa;
import org.sigma.core.domain.Rol;
import org.sigma.core.domain.Usuario;

privileged aspect Usuario_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "id_empresa", referencedColumnName = "id")
    private Empresa Usuario.idEmpresa;
    
    @ManyToOne
    @JoinColumn(name = "id_rol", referencedColumnName = "id")
    private Rol Usuario.idRol;
    
    @Column(name = "alias")
    private String Usuario.alias;
    
    @Column(name = "mail")
    private String Usuario.mail;
    
    @Column(name = "nombre")
    private String Usuario.nombre;
    
    public Empresa Usuario.getIdEmpresa() {
        return idEmpresa;
    }
    
    public void Usuario.setIdEmpresa(Empresa idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    
    public Rol Usuario.getIdRol() {
        return idRol;
    }
    
    public void Usuario.setIdRol(Rol idRol) {
        this.idRol = idRol;
    }
    
    public String Usuario.getAlias() {
        return alias;
    }
    
    public void Usuario.setAlias(String alias) {
        this.alias = alias;
    }
    
    public String Usuario.getMail() {
        return mail;
    }
    
    public void Usuario.setMail(String mail) {
        this.mail = mail;
    }
    
    public String Usuario.getNombre() {
        return nombre;
    }
    
    public void Usuario.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
